matchs_J1 = [
    ['Bilbao', 'Arsenal', [0, 2]],
    ['PSV', 'St Gillis', [1, 3]],
    ['Juventus', 'Dortmund', [4, 4]],
    ['Real Madrid', 'Marseille', [2, 1]],
    ['Benfica', 'Karabakh Agdam', [2, 3]],
    ['Tottenham', 'Villarreal', [1, 0]],
    ['Olympiakos', 'Paphos', [0, 0]],
    ['Slavia Praha', 'Bodoe Glimt', [2, 2]],
    ['Ajax', 'Inter', [0, 2]],
    ['Bayern', 'Chelsea', [3, 1]],
    ['Liverpool', 'Atletico', [3, 2]],
    ['Paris SG', 'Atalanta', [4, 0]],
    ['Brugge', 'Monaco', [4, 1]],
    ['FC Kobenhavn', 'Leverkusen', [2, 2]],
    ['Frankfurt', 'Galatasaray', [5, 1]],
    ['Man City', 'Napoli', [2, 0]],
    ['Newcastle', 'Barcelona', [1, 2]],
    ['Sporting', 'Kairat', [4, 1]],
]

matchs_J2 = [
    ['Atalanta', 'Brugge', [2, 1]],
    ['Kairat', 'Real Madrid', [0, 5]],
    ['Atletico', 'Frankfurt', [5, 1]],
    ['Chelsea', 'Benfica', [1, 0]],
    ['Inter', 'Slavia Praha', [3, 0]],
    ['Bodoe Glimt', 'Tottenham', [2, 2]],
    ['Galatasaray', 'Liverpool', [1, 0]],
    ['Marseille', 'Ajax', [4, 0]],
    ['Paphos', 'Bayern', [1, 5]],
    ['Karabakh Agdam', 'FC Kobenhavn', [2, 0]],
    ['St Gillis', 'Newcastle', [0, 4]],
    ['Arsenal', 'Olympiakos', [2, 0]],
    ['Monaco', 'Man City', [2, 2]],
    ['Leverkusen', 'PSV', [1, 1]],
    ['Dortmund', 'Bilbao', [4, 1]],
    ['Barcelona', 'Paris SG', [1, 2]],
    ['Napoli', 'Sporting', [2, 1]],
    ['Villarreal', 'Juventus', [2, 2]],
]

matchs_J3 = [
    ['Barcelona', 'Olympiakos', [6, 1]],
    ['Kairat', 'Paphos', [0, 0]],
    ['Arsenal', 'Atletico', [4, 0]],
    ['Leverkusen', 'Paris SG', [2, 7]],
    ['FC Kobenhavn', 'Dortmund', [2, 4]],
    ['Newcastle', 'Benfica', [3, 0]],
    ['PSV', 'Napoli', [6, 2]],
    ['St Gillis', 'Inter', [0, 4]],
    ['Villarreal', 'Man City', [0, 2]],
    ['Bilbao', 'Karabakh Agdam', [3, 1]],
    ['Galatasaray', 'Bodoe Glimt', [3, 1]],
    ['Monaco', 'Tottenham', [0, 0]],
    ['Atalanta', 'Slavia Praha', [0, 0]],
    ['Chelsea', 'Ajax', [5, 1]],
    ['Frankfurt', 'Liverpool', [1, 5]],
    ['Bayern', 'Brugge', [4, 0]],
    ['Real Madrid', 'Juventus', [1, 0]],
    ['Sporting', 'Marseille', [2, 1]],
]

matchs_J4 = [
    ['Slavia Praha', 'Arsenal', [0, 3]],
    ['Napoli', 'Frankfurt', [0, 0]],
    ['Atletico', 'St Gillis', [3, 1]],
    ['Bodoe Glimt', 'Monaco', [0, 1]],
    ['Juventus', 'Sporting', [1, 1]],
    ['Liverpool', 'Real Madrid', [1, 0]],
    ['Olympiakos', 'PSV', [1, 1]],
    ['Paris SG', 'Bayern', [1, 2]],
    ['Tottenham', 'FC Kobenhavn', [4, 0]],
    ['Paphos', 'Villarreal', [1, 0]],
    ['Karabakh Agdam', 'Chelsea', [2, 2]],
    ['Ajax', 'Galatasaray', [0, 3]],
    ['Brugge', 'Barcelona', [3, 3]],
    ['Inter', 'Kairat', [2, 1]],
    ['Man City', 'Dortmund', [4, 1]],
    ['Newcastle', 'Bilbao', [2, 0]],
    ['Marseille', 'Atalanta', [0, 1]],
    ['Benfica', 'Leverkusen', [0, 1]],
]

données_J1 = {
    'classement': ['Frankfurt', 'Paris SG', 'Brugge', 'Sporting', 'St Gillis', 'Bayern', 'Arsenal', 'Inter', 'Man City', 'Karabakh Agdam', 'Liverpool', 'Barcelona', 'Real Madrid', 'Tottenham', 'Dortmund', 'Juventus', 'Bodoe Glimt', 'Leverkusen', 'FC Kobenhavn', 'Slavia Praha', 'Olympiakos', 'Paphos', 'Atletico', 'Benfica', 'Marseille', 'Newcastle', 'Villarreal', 'Chelsea', 'PSV', 'Ajax', 'Bilbao', 'Napoli', 'Kairat', 'Monaco', 'Galatasaray', 'Atalanta'],
    'points': {
        'Ajax': 0,
        'Arsenal': 3,
        'Atalanta': 0,
        'Atletico': 0,
        'Barcelona': 3,
        'Bayern': 3,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 1,
        'Brugge': 3,
        'Chelsea': 0,
        'Dortmund': 1,
        'FC Kobenhavn': 1,
        'Frankfurt': 3,
        'Galatasaray': 0,
        'Inter': 3,
        'Juventus': 1,
        'Kairat': 0,
        'Karabakh Agdam': 3,
        'Leverkusen': 1,
        'Liverpool': 3,
        'Man City': 3,
        'Marseille': 0,
        'Monaco': 0,
        'Napoli': 0,
        'Newcastle': 0,
        'Olympiakos': 1,
        'PSV': 0,
        'Paphos': 1,
        'Paris SG': 3,
        'Real Madrid': 3,
        'Slavia Praha': 1,
        'Sporting': 3,
        'St Gillis': 3,
        'Tottenham': 3,
        'Villarreal': 0,
    },
    'diff_buts': {
        'Ajax': -2,
        'Arsenal': 2,
        'Atalanta': -4,
        'Atletico': -1,
        'Barcelona': 1,
        'Bayern': 2,
        'Benfica': -1,
        'Bilbao': -2,
        'Bodoe Glimt': 0,
        'Brugge': 3,
        'Chelsea': -2,
        'Dortmund': 0,
        'FC Kobenhavn': 0,
        'Frankfurt': 4,
        'Galatasaray': -4,
        'Inter': 2,
        'Juventus': 0,
        'Kairat': -3,
        'Karabakh Agdam': 1,
        'Leverkusen': 0,
        'Liverpool': 1,
        'Man City': 2,
        'Marseille': -1,
        'Monaco': -3,
        'Napoli': -2,
        'Newcastle': -1,
        'Olympiakos': 0,
        'PSV': -2,
        'Paphos': 0,
        'Paris SG': 4,
        'Real Madrid': 1,
        'Slavia Praha': 0,
        'Sporting': 3,
        'St Gillis': 2,
        'Tottenham': 1,
        'Villarreal': -1,
    },
    'buts': {
        'Ajax': 0,
        'Arsenal': 2,
        'Atalanta': 0,
        'Atletico': 2,
        'Barcelona': 2,
        'Bayern': 3,
        'Benfica': 2,
        'Bilbao': 0,
        'Bodoe Glimt': 2,
        'Brugge': 4,
        'Chelsea': 1,
        'Dortmund': 4,
        'FC Kobenhavn': 2,
        'Frankfurt': 5,
        'Galatasaray': 1,
        'Inter': 2,
        'Juventus': 4,
        'Kairat': 1,
        'Karabakh Agdam': 3,
        'Leverkusen': 2,
        'Liverpool': 3,
        'Man City': 2,
        'Marseille': 1,
        'Monaco': 1,
        'Napoli': 0,
        'Newcastle': 1,
        'Olympiakos': 0,
        'PSV': 1,
        'Paphos': 0,
        'Paris SG': 4,
        'Real Madrid': 2,
        'Slavia Praha': 2,
        'Sporting': 4,
        'St Gillis': 3,
        'Tottenham': 1,
        'Villarreal': 0,
    },
    'buts_ext': {
        'Ajax': 0,
        'Arsenal': 2,
        'Atalanta': 0,
        'Atletico': 2,
        'Barcelona': 2,
        'Bayern': 0,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 2,
        'Brugge': 0,
        'Chelsea': 1,
        'Dortmund': 4,
        'FC Kobenhavn': 0,
        'Frankfurt': 0,
        'Galatasaray': 1,
        'Inter': 2,
        'Juventus': 0,
        'Kairat': 1,
        'Karabakh Agdam': 3,
        'Leverkusen': 2,
        'Liverpool': 0,
        'Man City': 0,
        'Marseille': 1,
        'Monaco': 1,
        'Napoli': 0,
        'Newcastle': 0,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 0,
        'Real Madrid': 0,
        'Slavia Praha': 0,
        'Sporting': 0,
        'St Gillis': 3,
        'Tottenham': 0,
        'Villarreal': 0,
    },
    'nb_victoires': {
        'Ajax': 0,
        'Arsenal': 1,
        'Atalanta': 0,
        'Atletico': 0,
        'Barcelona': 1,
        'Bayern': 1,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 1,
        'Chelsea': 0,
        'Dortmund': 0,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 0,
        'Inter': 1,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 1,
        'Leverkusen': 0,
        'Liverpool': 1,
        'Man City': 1,
        'Marseille': 0,
        'Monaco': 0,
        'Napoli': 0,
        'Newcastle': 0,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 1,
        'Real Madrid': 1,
        'Slavia Praha': 0,
        'Sporting': 1,
        'St Gillis': 1,
        'Tottenham': 1,
        'Villarreal': 0,
    },
    'nb_victoires_ext': {
        'Ajax': 0,
        'Arsenal': 1,
        'Atalanta': 0,
        'Atletico': 0,
        'Barcelona': 1,
        'Bayern': 0,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 0,
        'Chelsea': 0,
        'Dortmund': 0,
        'FC Kobenhavn': 0,
        'Frankfurt': 0,
        'Galatasaray': 0,
        'Inter': 1,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 1,
        'Leverkusen': 0,
        'Liverpool': 0,
        'Man City': 0,
        'Marseille': 0,
        'Monaco': 0,
        'Napoli': 0,
        'Newcastle': 0,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 0,
        'Real Madrid': 0,
        'Slavia Praha': 0,
        'Sporting': 0,
        'St Gillis': 1,
        'Tottenham': 0,
        'Villarreal': 0,
    },
}

données_J2 = {
    'classement': ['Bayern', 'Real Madrid', 'Paris SG', 'Inter', 'Arsenal', 'Karabakh Agdam', 'Dortmund', 'Man City', 'Tottenham', 'Atletico', 'Newcastle', 'Marseille', 'Brugge', 'Sporting', 'Frankfurt', 'Barcelona', 'Liverpool', 'Chelsea', 'Napoli', 'St Gillis', 'Galatasaray', 'Atalanta', 'Juventus', 'Bodoe Glimt', 'Leverkusen', 'Villarreal', 'PSV', 'FC Kobenhavn', 'Olympiakos', 'Monaco', 'Slavia Praha', 'Paphos', 'Benfica', 'Bilbao', 'Ajax', 'Kairat'],
    'points': {
        'Ajax': 0,
        'Arsenal': 6,
        'Atalanta': 3,
        'Atletico': 3,
        'Barcelona': 3,
        'Bayern': 6,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 2,
        'Brugge': 3,
        'Chelsea': 3,
        'Dortmund': 4,
        'FC Kobenhavn': 1,
        'Frankfurt': 3,
        'Galatasaray': 3,
        'Inter': 6,
        'Juventus': 2,
        'Kairat': 0,
        'Karabakh Agdam': 6,
        'Leverkusen': 2,
        'Liverpool': 3,
        'Man City': 4,
        'Marseille': 3,
        'Monaco': 1,
        'Napoli': 3,
        'Newcastle': 3,
        'Olympiakos': 1,
        'PSV': 1,
        'Paphos': 1,
        'Paris SG': 6,
        'Real Madrid': 6,
        'Slavia Praha': 1,
        'Sporting': 3,
        'St Gillis': 3,
        'Tottenham': 4,
        'Villarreal': 1,
    },
    'diff_buts': {
        'Ajax': -6,
        'Arsenal': 4,
        'Atalanta': -3,
        'Atletico': 3,
        'Barcelona': 0,
        'Bayern': 6,
        'Benfica': -2,
        'Bilbao': -5,
        'Bodoe Glimt': 0,
        'Brugge': 2,
        'Chelsea': -1,
        'Dortmund': 3,
        'FC Kobenhavn': -2,
        'Frankfurt': 0,
        'Galatasaray': -3,
        'Inter': 5,
        'Juventus': 0,
        'Kairat': -8,
        'Karabakh Agdam': 3,
        'Leverkusen': 0,
        'Liverpool': 0,
        'Man City': 2,
        'Marseille': 3,
        'Monaco': -3,
        'Napoli': -1,
        'Newcastle': 3,
        'Olympiakos': -2,
        'PSV': -2,
        'Paphos': -4,
        'Paris SG': 5,
        'Real Madrid': 6,
        'Slavia Praha': -3,
        'Sporting': 2,
        'St Gillis': -2,
        'Tottenham': 1,
        'Villarreal': -1,
    },
    'buts': {
        'Ajax': 0,
        'Arsenal': 4,
        'Atalanta': 2,
        'Atletico': 7,
        'Barcelona': 3,
        'Bayern': 8,
        'Benfica': 2,
        'Bilbao': 1,
        'Bodoe Glimt': 4,
        'Brugge': 5,
        'Chelsea': 2,
        'Dortmund': 8,
        'FC Kobenhavn': 2,
        'Frankfurt': 6,
        'Galatasaray': 2,
        'Inter': 5,
        'Juventus': 6,
        'Kairat': 1,
        'Karabakh Agdam': 5,
        'Leverkusen': 3,
        'Liverpool': 3,
        'Man City': 4,
        'Marseille': 5,
        'Monaco': 3,
        'Napoli': 2,
        'Newcastle': 5,
        'Olympiakos': 0,
        'PSV': 2,
        'Paphos': 1,
        'Paris SG': 6,
        'Real Madrid': 7,
        'Slavia Praha': 2,
        'Sporting': 5,
        'St Gillis': 3,
        'Tottenham': 3,
        'Villarreal': 2,
    },
    'buts_ext': {
        'Ajax': 0,
        'Arsenal': 2,
        'Atalanta': 0,
        'Atletico': 2,
        'Barcelona': 2,
        'Bayern': 5,
        'Benfica': 0,
        'Bilbao': 1,
        'Bodoe Glimt': 2,
        'Brugge': 1,
        'Chelsea': 1,
        'Dortmund': 4,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 1,
        'Inter': 2,
        'Juventus': 2,
        'Kairat': 1,
        'Karabakh Agdam': 3,
        'Leverkusen': 2,
        'Liverpool': 0,
        'Man City': 2,
        'Marseille': 1,
        'Monaco': 1,
        'Napoli': 0,
        'Newcastle': 4,
        'Olympiakos': 0,
        'PSV': 1,
        'Paphos': 0,
        'Paris SG': 2,
        'Real Madrid': 5,
        'Slavia Praha': 0,
        'Sporting': 1,
        'St Gillis': 3,
        'Tottenham': 2,
        'Villarreal': 0,
    },
    'nb_victoires': {
        'Ajax': 0,
        'Arsenal': 2,
        'Atalanta': 1,
        'Atletico': 1,
        'Barcelona': 1,
        'Bayern': 2,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 1,
        'Chelsea': 1,
        'Dortmund': 1,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 1,
        'Inter': 2,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 2,
        'Leverkusen': 0,
        'Liverpool': 1,
        'Man City': 1,
        'Marseille': 1,
        'Monaco': 0,
        'Napoli': 1,
        'Newcastle': 1,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 2,
        'Real Madrid': 2,
        'Slavia Praha': 0,
        'Sporting': 1,
        'St Gillis': 1,
        'Tottenham': 1,
        'Villarreal': 0,
    },
    'nb_victoires_ext': {
        'Ajax': 0,
        'Arsenal': 1,
        'Atalanta': 0,
        'Atletico': 0,
        'Barcelona': 1,
        'Bayern': 1,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 0,
        'Chelsea': 0,
        'Dortmund': 0,
        'FC Kobenhavn': 0,
        'Frankfurt': 0,
        'Galatasaray': 0,
        'Inter': 1,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 1,
        'Leverkusen': 0,
        'Liverpool': 0,
        'Man City': 0,
        'Marseille': 0,
        'Monaco': 0,
        'Napoli': 0,
        'Newcastle': 1,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 1,
        'Real Madrid': 1,
        'Slavia Praha': 0,
        'Sporting': 0,
        'St Gillis': 1,
        'Tottenham': 0,
        'Villarreal': 0,
    },
}

données_J3 = {
    'classement': ['Paris SG', 'Bayern', 'Inter', 'Arsenal', 'Real Madrid', 'Dortmund', 'Man City', 'Newcastle', 'Barcelona', 'Liverpool', 'Sporting', 'Chelsea', 'Karabakh Agdam', 'Galatasaray', 'Tottenham', 'PSV', 'Atalanta', 'Marseille', 'Atletico', 'Brugge', 'Bilbao', 'Frankfurt', 'Napoli', 'St Gillis', 'Juventus', 'Bodoe Glimt', 'Monaco', 'Slavia Praha', 'Paphos', 'Leverkusen', 'Villarreal', 'FC Kobenhavn', 'Olympiakos', 'Kairat', 'Benfica', 'Ajax'],
    'points': {
        'Ajax': 0,
        'Arsenal': 9,
        'Atalanta': 4,
        'Atletico': 3,
        'Barcelona': 6,
        'Bayern': 9,
        'Benfica': 0,
        'Bilbao': 3,
        'Bodoe Glimt': 2,
        'Brugge': 3,
        'Chelsea': 6,
        'Dortmund': 7,
        'FC Kobenhavn': 1,
        'Frankfurt': 3,
        'Galatasaray': 6,
        'Inter': 9,
        'Juventus': 2,
        'Kairat': 1,
        'Karabakh Agdam': 6,
        'Leverkusen': 2,
        'Liverpool': 6,
        'Man City': 7,
        'Marseille': 3,
        'Monaco': 2,
        'Napoli': 3,
        'Newcastle': 6,
        'Olympiakos': 1,
        'PSV': 4,
        'Paphos': 2,
        'Paris SG': 9,
        'Real Madrid': 9,
        'Slavia Praha': 2,
        'Sporting': 6,
        'St Gillis': 3,
        'Tottenham': 5,
        'Villarreal': 1,
    },
    'diff_buts': {
        'Ajax': -10,
        'Arsenal': 8,
        'Atalanta': -3,
        'Atletico': -1,
        'Barcelona': 5,
        'Bayern': 10,
        'Benfica': -5,
        'Bilbao': -3,
        'Bodoe Glimt': -2,
        'Brugge': -2,
        'Chelsea': 3,
        'Dortmund': 5,
        'FC Kobenhavn': -4,
        'Frankfurt': -4,
        'Galatasaray': -1,
        'Inter': 9,
        'Juventus': -1,
        'Kairat': -8,
        'Karabakh Agdam': 1,
        'Leverkusen': -5,
        'Liverpool': 4,
        'Man City': 4,
        'Marseille': 2,
        'Monaco': -3,
        'Napoli': -5,
        'Newcastle': 6,
        'Olympiakos': -7,
        'PSV': 2,
        'Paphos': -4,
        'Paris SG': 10,
        'Real Madrid': 7,
        'Slavia Praha': -3,
        'Sporting': 3,
        'St Gillis': -6,
        'Tottenham': 1,
        'Villarreal': -3,
    },
    'buts': {
        'Ajax': 1,
        'Arsenal': 8,
        'Atalanta': 2,
        'Atletico': 7,
        'Barcelona': 9,
        'Bayern': 12,
        'Benfica': 2,
        'Bilbao': 4,
        'Bodoe Glimt': 5,
        'Brugge': 5,
        'Chelsea': 7,
        'Dortmund': 12,
        'FC Kobenhavn': 4,
        'Frankfurt': 7,
        'Galatasaray': 5,
        'Inter': 9,
        'Juventus': 6,
        'Kairat': 1,
        'Karabakh Agdam': 6,
        'Leverkusen': 5,
        'Liverpool': 8,
        'Man City': 6,
        'Marseille': 6,
        'Monaco': 3,
        'Napoli': 4,
        'Newcastle': 8,
        'Olympiakos': 1,
        'PSV': 8,
        'Paphos': 1,
        'Paris SG': 13,
        'Real Madrid': 8,
        'Slavia Praha': 2,
        'Sporting': 7,
        'St Gillis': 3,
        'Tottenham': 3,
        'Villarreal': 2,
    },
    'buts_ext': {
        'Ajax': 1,
        'Arsenal': 2,
        'Atalanta': 0,
        'Atletico': 2,
        'Barcelona': 2,
        'Bayern': 5,
        'Benfica': 0,
        'Bilbao': 1,
        'Bodoe Glimt': 3,
        'Brugge': 1,
        'Chelsea': 1,
        'Dortmund': 8,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 1,
        'Inter': 6,
        'Juventus': 2,
        'Kairat': 1,
        'Karabakh Agdam': 4,
        'Leverkusen': 2,
        'Liverpool': 5,
        'Man City': 4,
        'Marseille': 2,
        'Monaco': 1,
        'Napoli': 2,
        'Newcastle': 4,
        'Olympiakos': 1,
        'PSV': 1,
        'Paphos': 0,
        'Paris SG': 9,
        'Real Madrid': 5,
        'Slavia Praha': 0,
        'Sporting': 1,
        'St Gillis': 3,
        'Tottenham': 2,
        'Villarreal': 0,
    },
    'nb_victoires': {
        'Ajax': 0,
        'Arsenal': 3,
        'Atalanta': 1,
        'Atletico': 1,
        'Barcelona': 2,
        'Bayern': 3,
        'Benfica': 0,
        'Bilbao': 1,
        'Bodoe Glimt': 0,
        'Brugge': 1,
        'Chelsea': 2,
        'Dortmund': 2,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 2,
        'Inter': 3,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 2,
        'Leverkusen': 0,
        'Liverpool': 2,
        'Man City': 2,
        'Marseille': 1,
        'Monaco': 0,
        'Napoli': 1,
        'Newcastle': 2,
        'Olympiakos': 0,
        'PSV': 1,
        'Paphos': 0,
        'Paris SG': 3,
        'Real Madrid': 3,
        'Slavia Praha': 0,
        'Sporting': 2,
        'St Gillis': 1,
        'Tottenham': 1,
        'Villarreal': 0,
    },
    'nb_victoires_ext': {
        'Ajax': 0,
        'Arsenal': 1,
        'Atalanta': 0,
        'Atletico': 0,
        'Barcelona': 1,
        'Bayern': 1,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 0,
        'Chelsea': 0,
        'Dortmund': 1,
        'FC Kobenhavn': 0,
        'Frankfurt': 0,
        'Galatasaray': 0,
        'Inter': 2,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 1,
        'Leverkusen': 0,
        'Liverpool': 1,
        'Man City': 1,
        'Marseille': 0,
        'Monaco': 0,
        'Napoli': 0,
        'Newcastle': 1,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 2,
        'Real Madrid': 1,
        'Slavia Praha': 0,
        'Sporting': 0,
        'St Gillis': 1,
        'Tottenham': 0,
        'Villarreal': 0,
    },
}

données_J4 = {
    'classement': ['Bayern', 'Arsenal', 'Inter', 'Man City', 'Paris SG', 'Newcastle', 'Real Madrid', 'Liverpool', 'Galatasaray', 'Tottenham', 'Barcelona', 'Chelsea', 'Sporting', 'Dortmund', 'Karabakh Agdam', 'Atalanta', 'Atletico', 'PSV', 'Monaco', 'Paphos', 'Leverkusen', 'Brugge', 'Frankfurt', 'Napoli', 'Marseille', 'Juventus', 'Bilbao', 'St Gillis', 'Bodoe Glimt', 'Slavia Praha', 'Olympiakos', 'Villarreal', 'FC Kobenhavn', 'Kairat', 'Benfica', 'Ajax'],
    'points': {
        'Ajax': 0,
        'Arsenal': 12,
        'Atalanta': 7,
        'Atletico': 6,
        'Barcelona': 7,
        'Bayern': 12,
        'Benfica': 0,
        'Bilbao': 3,
        'Bodoe Glimt': 2,
        'Brugge': 4,
        'Chelsea': 7,
        'Dortmund': 7,
        'FC Kobenhavn': 1,
        'Frankfurt': 4,
        'Galatasaray': 9,
        'Inter': 12,
        'Juventus': 3,
        'Kairat': 1,
        'Karabakh Agdam': 7,
        'Leverkusen': 5,
        'Liverpool': 9,
        'Man City': 10,
        'Marseille': 3,
        'Monaco': 5,
        'Napoli': 4,
        'Newcastle': 9,
        'Olympiakos': 2,
        'PSV': 5,
        'Paphos': 5,
        'Paris SG': 9,
        'Real Madrid': 9,
        'Slavia Praha': 2,
        'Sporting': 7,
        'St Gillis': 3,
        'Tottenham': 8,
        'Villarreal': 1,
    },
    'diff_buts': {
        'Ajax': -13,
        'Arsenal': 11,
        'Atalanta': -2,
        'Atletico': 1,
        'Barcelona': 5,
        'Bayern': 11,
        'Benfica': -6,
        'Bilbao': -5,
        'Bodoe Glimt': -3,
        'Brugge': -2,
        'Chelsea': 3,
        'Dortmund': 2,
        'FC Kobenhavn': -8,
        'Frankfurt': -4,
        'Galatasaray': 2,
        'Inter': 10,
        'Juventus': -1,
        'Kairat': -9,
        'Karabakh Agdam': 1,
        'Leverkusen': -4,
        'Liverpool': 5,
        'Man City': 7,
        'Marseille': 1,
        'Monaco': -2,
        'Napoli': -5,
        'Newcastle': 8,
        'Olympiakos': -7,
        'PSV': 2,
        'Paphos': -3,
        'Paris SG': 9,
        'Real Madrid': 6,
        'Slavia Praha': -6,
        'Sporting': 3,
        'St Gillis': -8,
        'Tottenham': 5,
        'Villarreal': -4,
    },
    'buts': {
        'Ajax': 1,
        'Arsenal': 11,
        'Atalanta': 3,
        'Atletico': 10,
        'Barcelona': 12,
        'Bayern': 14,
        'Benfica': 2,
        'Bilbao': 4,
        'Bodoe Glimt': 5,
        'Brugge': 8,
        'Chelsea': 9,
        'Dortmund': 13,
        'FC Kobenhavn': 4,
        'Frankfurt': 7,
        'Galatasaray': 8,
        'Inter': 11,
        'Juventus': 7,
        'Kairat': 2,
        'Karabakh Agdam': 8,
        'Leverkusen': 6,
        'Liverpool': 9,
        'Man City': 10,
        'Marseille': 6,
        'Monaco': 4,
        'Napoli': 4,
        'Newcastle': 10,
        'Olympiakos': 2,
        'PSV': 9,
        'Paphos': 2,
        'Paris SG': 14,
        'Real Madrid': 8,
        'Slavia Praha': 2,
        'Sporting': 8,
        'St Gillis': 4,
        'Tottenham': 7,
        'Villarreal': 2,
    },
    'buts_ext': {
        'Ajax': 1,
        'Arsenal': 5,
        'Atalanta': 1,
        'Atletico': 2,
        'Barcelona': 5,
        'Bayern': 7,
        'Benfica': 0,
        'Bilbao': 1,
        'Bodoe Glimt': 3,
        'Brugge': 1,
        'Chelsea': 3,
        'Dortmund': 9,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 4,
        'Inter': 6,
        'Juventus': 2,
        'Kairat': 2,
        'Karabakh Agdam': 4,
        'Leverkusen': 3,
        'Liverpool': 5,
        'Man City': 4,
        'Marseille': 2,
        'Monaco': 2,
        'Napoli': 2,
        'Newcastle': 4,
        'Olympiakos': 1,
        'PSV': 2,
        'Paphos': 0,
        'Paris SG': 9,
        'Real Madrid': 5,
        'Slavia Praha': 0,
        'Sporting': 2,
        'St Gillis': 4,
        'Tottenham': 2,
        'Villarreal': 0,
    },
    'nb_victoires': {
        'Ajax': 0,
        'Arsenal': 4,
        'Atalanta': 2,
        'Atletico': 2,
        'Barcelona': 2,
        'Bayern': 4,
        'Benfica': 0,
        'Bilbao': 1,
        'Bodoe Glimt': 0,
        'Brugge': 1,
        'Chelsea': 2,
        'Dortmund': 2,
        'FC Kobenhavn': 0,
        'Frankfurt': 1,
        'Galatasaray': 3,
        'Inter': 4,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 2,
        'Leverkusen': 1,
        'Liverpool': 3,
        'Man City': 3,
        'Marseille': 1,
        'Monaco': 1,
        'Napoli': 1,
        'Newcastle': 3,
        'Olympiakos': 0,
        'PSV': 1,
        'Paphos': 1,
        'Paris SG': 3,
        'Real Madrid': 3,
        'Slavia Praha': 0,
        'Sporting': 2,
        'St Gillis': 1,
        'Tottenham': 2,
        'Villarreal': 0,
    },
    'nb_victoires_ext': {
        'Ajax': 0,
        'Arsenal': 2,
        'Atalanta': 1,
        'Atletico': 0,
        'Barcelona': 1,
        'Bayern': 2,
        'Benfica': 0,
        'Bilbao': 0,
        'Bodoe Glimt': 0,
        'Brugge': 0,
        'Chelsea': 0,
        'Dortmund': 1,
        'FC Kobenhavn': 0,
        'Frankfurt': 0,
        'Galatasaray': 1,
        'Inter': 2,
        'Juventus': 0,
        'Kairat': 0,
        'Karabakh Agdam': 1,
        'Leverkusen': 1,
        'Liverpool': 1,
        'Man City': 1,
        'Marseille': 0,
        'Monaco': 1,
        'Napoli': 0,
        'Newcastle': 1,
        'Olympiakos': 0,
        'PSV': 0,
        'Paphos': 0,
        'Paris SG': 2,
        'Real Madrid': 1,
        'Slavia Praha': 0,
        'Sporting': 0,
        'St Gillis': 1,
        'Tottenham': 0,
        'Villarreal': 0,
    },
}

